linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Optional ones we want to include
    - gochecknoinits
    - goconst
    - gocritic
    - goimports
    - gosec
    - misspell
    - nakedret
    - unconvert
    - unparam
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/ryo-yamaoka/paralleltest
  misspell:
    local: US
    ignore-words:

  govet:
    check-shadowing: true

output:
  format: colored-line-number
